# Generated by Django 6.0 on 2025-12-14 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Стабильный уникальный ключ концепта (используется в тексте/боте/API), например 'Product.Slab'.", max_length=500, unique=True)),
                ('label', models.CharField(blank=True, help_text='Человекочитаемое имя для UI. Если пусто — будет автоматически равно key.', max_length=500)),
                ('kind', models.CharField(choices=[('O', 'Объект (материальный)'), ('P', 'Процесс'), ('A', 'Актор'), ('I', 'Информация')], help_text='Верхний класс концепта (O/P/A/I).', max_length=1)),
                ('description', models.TextField(blank=True, help_text='Свободное описание/пояснение (не влияет на вычисления).')),
                ('is_active', models.BooleanField(default=True, help_text='Технический флаг: активен ли концепт (для UI/фильтрации).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'navis_concept',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=6, help_text='Необязательный технический вес связи (не использовать для доменной семантики).', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'navis_edge',
            },
        ),
        migrations.CreateModel(
            name='EdgeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Имя атрибута (для MVP: 'confidence', 'source_message_id').", max_length=100)),
                ('value_text', models.TextField(help_text="Значение атрибута в текстовом виде (для MVP: '0.95', '1234567890').")),
            ],
            options={
                'db_table': 'navis_edge_attr',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Каноническое имя типа связи, например 'describes', 'is_a', 'part_of'.", max_length=100, unique=True)),
                ('alias', models.CharField(blank=True, help_text="Текстовый алиас (оператор) для сообщений, например '-?->'. Может быть пустым для служебных типов связи.", max_length=20, null=True, unique=True)),
                ('label', models.CharField(help_text="Человекочитаемое имя типа связи, например 'Описывает', 'Является', 'Часть'.", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Пояснение смысла типа связи (для справки/документации).')),
                ('is_base', models.BooleanField(default=False, help_text='Если True — тип связи разрешён как базовый оператор для ввода пользователем/ботом и для UI.')),
                ('is_active', models.BooleanField(default=True, help_text='Технический флаг активности типа связи.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'navis_relation_type',
            },
        ),
        migrations.CreateModel(
            name='CalcBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_key', models.CharField(help_text="Уникальный ключ блока (для MVP: 'CAPEX', 'Production', 'UnitCosts', 'PnL', 'CashFlow').", max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'calc_block',
                'indexes': [models.Index(fields=['block_key'], name='calc_block_block_k_7daca0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalcBlockFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(help_text='Блок, в который входит формула (для MVP: CAPEX, Production, UnitCosts, PnL, CashFlow).', on_delete=django.db.models.deletion.CASCADE, related_name='block_formulas', to='navis_tdjango.calcblock')),
            ],
            options={
                'db_table': 'calc_block_formula',
            },
        ),
        migrations.CreateModel(
            name='CalcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(help_text="Уникальный ключ модели расчёта (для MVP: 'invest.pnl_cf.v1').", max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'calc_model',
                'indexes': [models.Index(fields=['model_key'], name='calc_model_model_k_991cd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalcModelAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField(help_text='Порядок исполнения блока (меньше — раньше; для MVP: 1, 2, 3, 4, 5).')),
                ('block', models.ForeignKey(help_text='Блок, входящий в модель (для MVP: CAPEX, Production, UnitCosts, PnL, CashFlow).', on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='navis_tdjango.calcblock')),
                ('model', models.ForeignKey(help_text='Модель расчёта (для MVP: invest.pnl_cf.v1).', on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='navis_tdjango.calcmodel')),
            ],
            options={
                'db_table': 'calc_model_assembly',
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('concept', models.OneToOneField(help_text="Концепт формулы (обычно kind='I' и типизирован как I.Formula через is_a) для вычислений.", on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='formula', serialize=False, to='navis_tdjango.concept')),
                ('language', models.CharField(default='expr', help_text="Язык выражения (для MVP: 'expr' — простая арифметика).", max_length=30)),
                ('expression', models.TextField(help_text="Текст исполняемого выражения (без присваивания; для MVP: 'PRICE_P * VOLUME').")),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'navis_formula',
            },
        ),
        migrations.CreateModel(
            name='InfoValue',
            fields=[
                ('concept', models.OneToOneField(help_text='Информационный концепт (I-концепт), для которого хранится значение.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info_value', serialize=False, to='navis_tdjango.concept')),
                ('value_num', models.DecimalField(blank=True, decimal_places=10, help_text='Числовое значение (для финансов/инженерии; для MVP: Price = 100, Volume = 1000).', max_digits=30, null=True)),
                ('value_text', models.TextField(blank=True, help_text="Текстовое значение (если I-концепт не числовой; для MVP: 'USD', 'EUR').", null=True)),
                ('unit', models.CharField(blank=True, help_text="Единица измерения (для MVP: 'USD', 'EUR').", max_length=50)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'navis_info_value',
            },
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['kind'], name='navis_conce_kind_41aa18_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['is_active'], name='navis_conce_is_acti_27d018_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['updated_at'], name='navis_conce_updated_aa12a6_idx'),
        ),
        migrations.AddField(
            model_name='calcblockformula',
            name='formula_concept',
            field=models.ForeignKey(help_text="Концепт формулы (обычно kind='I' и тип I.Formula через is_a) для вычислений.", on_delete=django.db.models.deletion.PROTECT, related_name='as_block_formula', to='navis_tdjango.concept'),
        ),
        migrations.AddField(
            model_name='edge',
            name='from_concept',
            field=models.ForeignKey(help_text='Исходный концепт (откуда идёт связь).', on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='navis_tdjango.concept'),
        ),
        migrations.AddField(
            model_name='edge',
            name='to_concept',
            field=models.ForeignKey(help_text='Целевой концепт (куда указывает связь).', on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='navis_tdjango.concept'),
        ),
        migrations.AddField(
            model_name='edgeattribute',
            name='edge',
            field=models.ForeignKey(help_text="Ребро, к которому относится атрибут (для MVP: Edge(relation_type='describes')).", on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='navis_tdjango.edge'),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Родительский тип связи в иерархии разновидностей связи. Для корневого 'relation' = NULL.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='navis_tdjango.relationtype'),
        ),
        migrations.AddField(
            model_name='edge',
            name='relation_type',
            field=models.ForeignKey(help_text='Тип связи (управляется данными, включает алиасы и иерархию).', on_delete=django.db.models.deletion.PROTECT, related_name='edges', to='navis_tdjango.relationtype'),
        ),
        migrations.AddIndex(
            model_name='calcmodelassembly',
            index=models.Index(fields=['model', 'order_no'], name='calc_model__model_i_10cb88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calcmodelassembly',
            unique_together={('model', 'block')},
        ),
        migrations.AddIndex(
            model_name='formula',
            index=models.Index(fields=['language'], name='navis_formu_languag_db07ee_idx'),
        ),
        migrations.AddIndex(
            model_name='formula',
            index=models.Index(fields=['updated_at'], name='navis_formu_updated_0dc3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='infovalue',
            index=models.Index(fields=['updated_at'], name='navis_info__updated_f7d72d_idx'),
        ),
        migrations.AddIndex(
            model_name='infovalue',
            index=models.Index(fields=['unit'], name='navis_info__unit_f42176_idx'),
        ),
        migrations.AddIndex(
            model_name='calcblockformula',
            index=models.Index(fields=['block', 'formula_concept'], name='calc_block__block_i_54d3ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calcblockformula',
            unique_together={('block', 'formula_concept')},
        ),
        migrations.AddIndex(
            model_name='edgeattribute',
            index=models.Index(fields=['key'], name='navis_edge__key_21be29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='edgeattribute',
            unique_together={('edge', 'key')},
        ),
        migrations.AddIndex(
            model_name='relationtype',
            index=models.Index(fields=['is_base'], name='navis_relat_is_base_a1e3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='relationtype',
            index=models.Index(fields=['is_active'], name='navis_relat_is_acti_525cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='relationtype',
            index=models.Index(fields=['parent'], name='navis_relat_parent__eaa967_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['from_concept', 'relation_type'], name='navis_edge_from_co_ac482e_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['to_concept', 'relation_type'], name='navis_edge_to_conc_ee9619_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['relation_type'], name='navis_edge_relatio_d7b1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['updated_at'], name='navis_edge_updated_430db1_idx'),
        ),
    ]
