# Generated by Django 6.0 on 2025-12-17 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navis_tdjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='root_lv2',
            field=models.ForeignKey(blank=True, help_text='Родительский концепт первого уровня (NULL для концептов первого уровня).', limit_choices_to={'root_lv2__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_lv2', to='navis_tdjango.concept'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['root_lv2'], name='navis_conce_root_lv_4a7f2d_idx'),
        ),
    ]
